// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1iXs7_6FdR0eY0MpvP-v6bsgCK_TbV_0',
    appId: '1:101467299658:web:fe62a1812c26f8ff0bebb3',
    messagingSenderId: '101467299658',
    projectId: 'fitness-tracker-app-2026',
    authDomain: 'fitness-tracker-app-2026.firebaseapp.com',
    storageBucket: 'fitness-tracker-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2GUSfXRkaXEpoHGDwK5b-JaK1_A0zDI',
    appId: '1:101467299658:android:aabb3c67bb94bd350bebb3',
    messagingSenderId: '101467299658',
    projectId: 'fitness-tracker-app-2026',
    storageBucket: 'fitness-tracker-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbnGtnoUKA480HL0HqzD49_7KTRznvji4',
    appId: '1:101467299658:ios:eb37b224b9fbb1200bebb3',
    messagingSenderId: '101467299658',
    projectId: 'fitness-tracker-app-2026',
    storageBucket: 'fitness-tracker-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbnGtnoUKA480HL0HqzD49_7KTRznvji4',
    appId: '1:101467299658:ios:eb37b224b9fbb1200bebb3',
    messagingSenderId: '101467299658',
    projectId: 'fitness-tracker-app-2026',
    storageBucket: 'fitness-tracker-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1iXs7_6FdR0eY0MpvP-v6bsgCK_TbV_0',
    appId: '1:101467299658:web:62016c663be4c7910bebb3',
    messagingSenderId: '101467299658',
    projectId: 'fitness-tracker-app-2026',
    authDomain: 'fitness-tracker-app-2026.firebaseapp.com',
    storageBucket: 'fitness-tracker-app-2026.firebasestorage.app',
  );
}
